apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-gateway
  template: 
    metadata:
      labels:
        app: deployment-gateway  
    spec:
      containers:
      - name: deployment-gateway
        image: furkanbalbasio/gatewayservefirst:v001
        ##docker da bulunan image
        resources:
          limits:
            cpu: "300m"
            memory: "1024Mi"
        ports:
        - containerPort: 80
        ## yml de tanimlanan server portu aliyoruz.
        env:
          - name: CONFIG_SERVER
            value: http://10.12.0.62:8888

