apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deployment-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      db: deployment-mongodb-label
  template:
    metadata:
      labels:
        db: deployment-mongodb-label
    spec:
      containers:
      - name: mongodb
        image: mongo
        resources:
          limits:
            memory: "2048Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "BilgeAdmin"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "BilgeAdam!!**"      

